#!/usr/bin/env python3
"""
NSE Dashboard 2 — Average Entry-Day Return (6-Month)
============================================
Metric: For each stock, fix the END date at the latest close.
Then for EVERY trading day in the past 6 months, compute the return from
buying that day and holding to the latest close:

    return(d) = (P_last - P_d) / P_d * 100

The headline number is the AVERAGE of all those returns:
"On average, if I had bought on each day in the past 6 months and held to
 the latest close, what return would I have?"

Also reports: best/worst single entry day, % of entry days profitable,
and median, since they come free from the same calculation.

Usage:
    python3 fetch_data2.py             # fetch ALL stocks
    python3 fetch_data2.py --limit 50  # fetch only first 50 (test run)
    python3 fetch_data2.py --start 50 --limit 50   # fetch stocks 50..99
"""

import sys
import os
import json
import argparse
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd
import numpy as np

import time
import random

# Try curl_cffi for browser-impersonating sessions. On some Python builds
# (e.g. 3.14) its binary fails to load; we force the load here so any such
# failure is caught now and we cleanly fall back to plain requests.
try:
    from curl_cffi import requests as cffi_requests
    _probe = cffi_requests.Session  # touch attribute to trigger lazy binary load
    _HAS_CFFI = True
except Exception:
    _HAS_CFFI = False

import yfinance as yf

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "docs" / "data"
DATA_DIR.mkdir(exist_ok=True)

# ── Stock universe (NSE symbols, user-supplied) ───────────────────────────────
NSE_STOCKS = [
    "ORBTEXP",
    "SONATSOFTW",
    "NIITLTD",
    "RPTECH",
    "TARSONS",
    "XPROINDIA",
    "CEWATER",
    "MSTCLTD",
    "LLOYDSENGG",
    "FACT",
    "GRANDOAK",
    "FINKURVE",
    "ORCHPHARMA",
    "MCLOUD",
    "FABTECH",
    "KRONOX",
    "QUADFUTURE",
    "TCPLPACK",
    "EMBDL",
    "SIMPLEXINF",
    "PREMEXPLN",
    "MMTC",
    "RGL",
    "WABAG",
    "ZUARI",
    "RIIL",
    "SHK",
    "CMPDI",
    "PGEL",
    "ASHIANA",
    "VARROC",
    "HCC",
    "ADFFOODS",
    "ESAFSFB",
    "AGI",
    "ABREL",
    "MARINE",
    "AYE",
    "JAINREC",
    "IVALUE",
    "GODAVARIB",
    "NETWEB",
    "NILE",
    "CAPACITE",
    "MUTHOOTMF",
    "KALPATARU",
    "HUBTOWN",
    "MENONBE",
    "RML",
    "JAICORPLTD",
    "JAYBARMARU",
    "GRMOVER",
    "BRIGADE",
    "EDELWEISS",
    "PANSARI",
    "GKENERGY",
    "PARADEEP",
    "INNOVANA",
    "GNFC",
    "DENTA",
    "ATLANTAELE",
    "IZMO",
    "GVPIL",
    "IDEAFORGE",
    "SEJALLTD",
    "DEEDEV",
    "BHAGYANGR",
    "CHEMBONDCH",
    "RAJESHEXPO",
    "SICALLOG",
    "VIDYAWIRES",
    "SUBEXLTD",
    "GAYAPROJ",
    "NCLIND",
    "VASCONEQ",
    "SUNTECK",
    "ZUARIIND",
    "SOTL",
    "PDSL",
    "MTARTECH",
    "PRECWIRE",
    "DECNGOLD",
    "KPIL",
    "SAPPHIRE",
    "HFCL",
    "MOL",
    "FRACTAL",
    "MAXESTATES",
    "KKCL",
    "BHARATWIRE",
    "SADHNANIQ",
    "GHCLTEXTIL",
    "NACLIND",
    "COFORGE",
    "NUCLEUS",
    "POKARNA",
    "MUKKA",
    "AJMERA",
    "FCL",
    "RANEHOLDIN",
    "TBZ",
    "ADVAIT",
    "NAVKARCORP",
    "SUZLON",
    "NEPHROPLUS",
    "RAMCOSYS",
    "PARACABLES",
    "THEJO",
    "AVL",
    "BNAGROCHEM",
    "SPARC",
    "MGL",
    "MANAKCOAT",
    "HARSHA",
    "EUROPRATIK",
    "TITAGARH",
    "SPIC",
    "RHETAN",
    "MADRASFERT",
    "EXICOM",
    "ARFIN",
    "RAMRAT",
    "ANUHPHR",
    "INVPRECQ",
    "WELSPLSOL",
    "MANBA",
    "GLAXO",
    "CCAVENUE",
    "PATELENG",
    "NETWORK18",
    "APTECHT",
    "COROMANDEL",
    "SHILPAMED",
    "ZENTEC",
    "KIRLOSBROS",
    "AHLUCONT",
    "HCLTECH",
    "EXPLEOSOL",
    "GOLDIAM",
    "NIITMTS",
    "SOLEX",
    "ASTEC",
    "NAZARA",
    "SINDHUTRAD",
    "NRL",
    "SBICARD",
    "ITDC",
    "LIKHITHA",
    "MAYURUNIQ",
    "CHAMBLFERT",
    "SKMEGGPROD",
    "LAXMIINDIA",
    "PRESTIGE",
    "APOLLO",
    "VLSFINANCE",
    "TIMKEN",
    "JSWHL",
    "AWL",
    "DHUNINV",
    "PYRAMID",
    "FOSECOIND",
    "MCCHRLS-B",
    "ORISSAMINE",
    "KAYNES",
    "CUB",
    "BORORENEW",
    "HSCL",
    "SASKEN",
    "SCHAEFFLER",
    "KLBRENG-B",
    "BETA",
    "INOXINDIA",
    "KAJARIACER",
    "KOLTEPATIL",
    "ZENSARTECH",
    "COSMOFIRST",
    "ROUTE",
    "KEC",
    "MASTEK",
    "ICICIGI",
    "JAMNAAUTO",
    "JAYKAY",
    "BLISSGVS",
    "GLOBAL",
    "OSWALAGRO",
    "LTM",
    "SIGMAADV",
    "IXIGO",
    "5PAISA",
    "BANDHANBNK",
    "TATACONSUM",
    "MONARCH",
    "TEGA",
    "RELAXO",
    "MAHLIFE",
    "STCINDIA",
    "EIEL",
    "JKCEMENT",
    "GUFICBIO",
    "AURUM",
    "LGEINDIA",
    "JAYAGROGN",
    "NFL",
    "STLTECH",
    "PERSISTENT",
    "SALZERELEC",
    "ONMOBILE",
    "RCF",
    "KANORICHEM",
    "GENUSPOWER",
    "INGERRAND",
    "HPL",
    "CARTRADE",
    "HERITGFOOD",
    "STANLEY",
    "VADILALIND",
    "AMBER",
    "DMART",
    "DEVYANI",
    "GESHIP",
    "ZEEL",
    "SMARTWORKS",
    "IGPL",
    "NBIFIN",
    "GREENLAM",
    "AETHER",
    "LOKESHMACH",
    "PTC",
    "DLF",
    "BHAGERIA",
    "RATEGAIN",
    "DIFFNKG",
    "TINNARUBR",
    "BALMLAWRIE",
    "MAMATA",
    "CREDITACC",
    "ORIENTELEC",
    "INDIGOPNTS",
    "DIXON",
    "KTKBANK",
    "CELLO",
    "FINEORG",
    "JISLJALEQS",
    "E2E",
    "GALAXYSURF",
    "HMVL",
    "NOVARTIND",
    "INDIQUBE",
    "SHREERAMA",
    "BDL",
    "ZYDUSWELL",
    "ARVINDFASN",
    "BIRLACABLE",
    "LLOYDSENT",
    "AEGISVOPAK",
    "RSYSTEMS",
    "GOCOLORS",
    "WCIL",
    "BFUTILITIE",
    "UNITDSPR",
    "FUSION",
    "AURIONPRO",
    "PAISALO",
    "CEINSYS",
    "CREST",
    "NTPC",
    "PREMIERPOL",
    "ECLERX",
    "SUYOG",
    "KSOLVES",
    "BAJAJFINSV",
    "OBEROIRLTY",
    "MALLCOM",
    "RELIGARE",
    "AMAGI",
    "HDBFS",
    "TIRUPATIFL",
    "MAPMYINDIA",
    "SBCL",
    "BIKAJI",
    "IONEXCHANG",
    "GNA",
    "HINDUNILVR",
    "INTERARCH",
    "3MINDIA",
    "GEOJITFSL",
    "ELANTAS",
    "GMDCLTD",
    "GAUDIUMIVF",
    "KECL",
    "HONAUT",
    "LTTS",
    "SPANDANA",
    "MARSONS",
    "MCLEODRUSS",
    "PRINCEPIPE",
    "ALOKINDS",
    "WAAREEINDO",
    "KIOCL",
    "HEALTHX",
    "PATELRMART",
    "KELLTONTEC",
    "SANOFI",
    "KAMAHOLD",
    "DOMS",
    "CLEANMAX",
    "BUILDPRO",
    "PROTEAN",
    "CESC",
    "INTLCONV",
    "COLPAL",
    "CAMS",
    "TARIL",
    "VISAKAIND",
    "NAVA",
    "CLSEL",
    "REFEX",
    "SAGCEM",
    "ESSARSHPNG",
    "STYRENIX",
    "ONGC",
    "LODHA",
    "AJAXENGG",
    "JUBLINGREA",
    "HOMEFIRST",
    "TRANSPEK",
    "BAJFINANCE",
    "DYCL",
    "BIRLACORPN",
    "BHARATCOAL",
    "KAMDHENU",
    "PENINLAND",
    "KARURVYSYA",
    "SETL",
    "TIRUMALCHM",
    "VIKRAN",
    "ORKLAINDIA",
    "LINC",
    "DEEPAKFERT",
    "SRM",
    "TENNIND",
    "BALKRISIND",
    "JYOTICNC",
    "GHCL",
    "CHEMPLASTS",
    "BAJAJHLDNG",
    "INDIAMART",
    "QUESS",
    "CGCL",
    "SUTLEJTEX",
    "EMCURE",
    "ELECTHERM",
    "POWERICA",
    "CAPITALSFB",
    "PLATIND",
    "TCS",
    "INNOVACAP",
    "PENIND",
    "KENNAMET",
    "TREL",
    "PFS",
    "ARMANFIN",
    "POCL",
    "KFINTECH",
    "ANDHRAPAP",
    "RELIANCE",
    "POLYPLEX",
    "SPMLINFRA",
    "NBCC",
    "EIFFL",
    "MOSCHIP",
    "ENRIN",
    "SGIL",
    "GENESYS",
    "PETRONET",
    "CHOLAFIN",
    "SOBHA",
    "ARVSMART",
    "LALPATHLAB",
    "SCODATUBES",
    "GODREJPROP",
    "STAR",
    "EMIL",
    "SEDEMAC",
    "NEWGEN",
    "GEMAROMA",
    "SNOWMAN",
    "DIVISLAB",
    "METROPOLIS",
    "HUDCO",
    "PROZONER",
    "UTKARSHBNK",
    "NAUKRI",
    "COALINDIA",
    "TANLA",
    "PIIND",
    "BFINVEST",
    "GEECEE",
    "SUMEETINDS",
    "ASTRAMICRO",
    "ABCAPITAL",
    "SWSOLAR",
    "MUNJALAU",
    "GTPL",
    "KINGFA",
    "TECHM",
    "TVSELECT",
    "ARIHANTSUP",
    "ALGOQUANT",
    "CRISIL",
    "TRAVELFOOD",
    "DABUR",
    "UTLSOLAR",
    "DCXINDIA",
    "INOXGREEN",
    "UNICHEMLAB",
    "FOCUS",
    "KIRLOSIND",
    "VALIANTORG",
    "GSFC",
    "ABB",
    "INDNIPPON",
    "HALDYNGL",
    "AVANTEL",
    "GICHSGFIN",
    "COCHINSHIP",
    "GVT&D",
    "KRBL",
    "SHIVAUM",
    "BHARATSE",
    "ADSL",
    "KNRCON",
    "PARKHOTELS",
    "SARLAPOLY",
    "KNAGRI",
    "OFSS",
    "HDFCAMC",
    "GULFOILLUB",
    "BAJAJCON",
    "TORNTPOWER",
    "NELCO",
    "BALRAMCHIN",
    "SAATVIKGL",
    "EMSLIMITED",
    "RPOWER",
    "RECLTD",
    "FLAIR",
    "MEDANTA",
    "INDOSTAR",
    "VENTIVE",
    "PRAJIND",
    "NESCO",
    "LICI",
    "NORTHARC",
    "HIKAL",
    "ITC",
    "J&KBANK",
    "ONEPOINT",
    "KOTHARIPET",
    "TITAN",
    "JLHL",
    "SAMHI",
    "TEXRAIL",
    "COHANCE",
    "TRIDENT",
    "TATAELXSI",
    "EIDPARRY",
    "TTKPRESTIG",
    "SHRINGARMS",
    "ASTRAL",
    "NESTLEIND",
    "JSL",
    "BOMDYEING",
    "63MOONS",
    "ESTER",
    "WINDLAS",
    "BLUEJET",
    "JTEKTINDIA",
    "GRINDWELL",
    "VIJAYA",
    "TECHNOE",
    "RAYMONDLSL",
    "STYLEBAAZA",
    "WALCHANNAG",
    "INDPRUD",
    "KSB",
    "CYIENT",
    "MAXIND",
    "TIINDIA",
    "SOMANYCERA",
    "DATAPATTNS",
    "EMUDHRA",
    "PHOENIXLTD",
    "APARINDS",
    "KIMS",
    "SIGNATURE",
    "DIAMONDYD",
    "MAZDOCK",
    "IIFL",
    "FEDERALBNK",
    "CIFL",
    "CORONA",
    "FINCABLES",
    "TNPETRO",
    "NIVABUPA",
    "AVTNPL",
    "APLLTD",
    "BOROSCI",
    "TEXINFRA",
    "SUNFLAG",
    "IREDA",
    "CHOICEIN",
    "JMFINANCIL",
    "YATRA",
    "DPSCLTD",
    "KIRLPNU",
    "BAJAJHCARE",
    "ESCORTS",
    "ARIHANT",
    "TCIEXP",
    "SPECIALITY",
    "SHANTIGEAR",
    "INOXWIND",
    "JIOFIN",
    "FEDDERSHOL",
    "CENTRUM",
    "SHARDAMOTR",
    "UNIPARTS",
    "JAGRAN",
    "POLICYBZR",
    "GMMPFAUDLR",
    "WPIL",
    "POONAWALLA",
    "LAOPALA",
    "MICEL",
    "CIEINDIA",
    "GREENPLY",
    "SHINDL",
    "SIEMENS",
    "HDFCBANK",
    "KITEX",
    "SULA",
    "VENUSPIPES",
    "IRCTC",
    "RAILTEL",
    "SURYODAY",
    "PGHH",
    "GRWRHITECH",
    "ADANIPORTS",
    "PREMIERENE",
    "GALAPREC",
    "OMNI",
    "SWIGGY",
    "ASTRAZEN",
    "MIDWESTLTD",
    "CHALET",
    "PCBL",
    "ADANIPOWER",
    "VAKRANGEE",
    "TIIL",
    "ASKAUTOLTD",
    "WEBELSOLAR",
    "DHANBANK",
    "AUTOAXLES",
    "JKIL",
    "INDIASHLTR",
    "RITES",
    "CHOLAHLDNG",
    "KRISHNADEF",
    "VESUVIUS",
    "AMIRCHAND",
    "PTL",
    "SUDARSCHEM",
    "BSE",
    "MBEL",
    "MSPL",
    "KERNEX",
    "CONCOR",
    "NIACL",
    "SRF",
    "BLACKBUCK",
    "ICICIPRULI",
    "USHAMART",
    "IRCON",
    "NEOGEN",
    "SEIL",
    "TIMETECHNO",
    "IRB",
    "EMAMILTD",
    "MEIL",
    "DMCC",
    "AJANTPHARM",
    "HIRECT",
    "HBLENGINE",
    "RHIM",
    "ASIANHOTNR",
    "HITECH",
    "UNITECH",
    "SKIPPER",
    "SWARAJENG",
    "GODREJAGRO",
    "PANAMAPET",
    "PWL",
    "GREENPOWER",
    "PRUDENT",
    "KMEW",
    "GANDHITUBE",
    "PICCADIL",
    "WSTCSTPAPR",
    "BAJAJELEC",
    "GMRAIRPORT",
    "DVL",
    "GIPCL",
    "HAVELLS",
    "STEL",
    "KILITCH",
    "PILANIINVS",
    "VENKEYS",
    "SIKA",
    "INFY",
    "PANACEABIO",
    "UJJIVANSFB",
    "MPHASIS",
    "EIMCOELECO",
    "VGUARD",
    "LINDEINDIA",
    "SUNDROP",
    "LENSKART",
    "DOLPHIN",
    "WINDMACHIN",
    "GAEL",
    "CARYSIL",
    "SJVN",
    "SJS",
    "EBGNG",
    "PFC",
    "WIPRO",
    "BBTC",
    "JUSTDIAL",
    "DELTACORP",
    "VEEDOL",
    "MANGLMCEM",
    "LATENTVIEW",
    "JPOLYINVST",
    "MINDTECK",
    "GANESHCP",
    "PRSMJOHNSN",
    "NDTV",
    "KPIGREEN",
    "SURAKSHA",
    "JINDALPHOT",
    "CANFINHOME",
    "INDHOTEL",
    "IIFLCAPS",
    "JKLAKSHMI",
    "JINDALSAW",
    "JTLIND",
    "BHARTIARTL",
    "RESPONIND",
    "OMAXE",
    "SHILCTECH",
    "RRKABEL",
    "BLUESTARCO",
    "ANANTRAJ",
    "MOIL",
    "ETERNAL",
    "GALLANTT",
    "MMFL",
    "BALUFORGE",
    "MIDHANI",
    "WOCKPHARMA",
    "INSECTICID",
    "REGAAL",
    "WAAREERTL",
    "KRISHANA",
    "AFCONS",
    "RVNL",
    "EPACK",
    "EPL",
    "LGHL",
    "SOUTHBANK",
    "OIL",
    "WELSPUNLIV",
    "HEMIPROP",
    "ABLBL",
    "SCILAL",
    "ORIENTTECH",
    "LAXMIDENTL",
    "PRADPME",
    "EMKAY",
    "IRFC",
    "UCOBANK",
    "CAPLIPOINT",
    "SUMMITSEC",
    "CGPOWER",
    "SUNDRMFAST",
    "APCOTEXIND",
    "IGARASHI",
    "STYL",
    "SBFC",
    "IOB",
    "VOLTAMP",
    "RUBICON",
    "PVRINOX",
    "DATAMATICS",
    "WEWORK",
    "OPTIEMUS",
    "MANYAVAR",
    "KOTAKBANK",
    "DHARMAJ",
    "KROSS",
    "ECOSMOBLTY",
    "JUBLCPL",
    "TATVA",
    "SHRIRAMFIN",
    "MOTILALOFS",
    "APOLLOTYRE",
    "MASFIN",
    "ASHOKLEY",
    "SERVOTECH",
    "SANOFICONR",
    "AIAENG",
    "DSSL",
    "ICICIBANK",
    "MARATHON",
    "GARUDA",
    "IEX",
    "BBOX",
    "REDINGTON",
    "INDSWFTLAB",
    "DOLATALGO",
    "RAJRILTD",
    "BPCL",
    "FEDFINA",
    "CANBK",
    "SUPREMEIND",
    "SANDESH",
    "JWL",
    "PURVA",
    "UGROCAP",
    "SBILIFE",
    "NATCOPHARM",
    "ITI",
    "VRLLOG",
    "YESBANK",
    "WAAREEENER",
    "APLAPOLLO",
    "BEEKAY",
    "DBREALTY",
    "AZAD",
    "INDIANB",
    "PANACHE",
    "TCC",
    "VIPIND",
    "WANBURY",
    "CANTABIL",
    "PNCINFRA",
    "IOC",
    "JINDWORLD",
    "TEAMLEASE",
    "HGINFRA",
    "SAREGAMA",
    "SANDUMA",
    "KHAICHEM",
    "IBULLSLTD",
    "BASF",
    "CENTENKA",
    "SUNTV",
    "TRUALT",
    "CENTRALBK",
    "LT",
    "GLOBUSSPR",
    "SUDEEPPHRM",
    "GANESHHOU",
    "OAL",
    "KOTIC",
    "ARKADE",
    "HTMEDIA",
    "NAVINFLUOR",
    "RATNAMANI",
    "MPSLTD",
    "POLYMED",
    "SPLPETRO",
    "GLOSTERLTD",
    "SONACOMS",
    "ROSSARI",
    "INDGN",
    "SENCO",
    "EIHAHOTELS",
    "PRAVEG",
    "GAIL",
    "SHAKTIPUMP",
    "SOUTHWEST",
    "POLYCAB",
    "WONDERLA",
    "EQUITASBNK",
    "KOVAI",
    "BRITANNIA",
    "IFBIND",
    "BHEL",
    "ROHLTD",
    "EFCIL",
    "IDBI",
    "STLNETWORK",
    "NITINSPIN",
    "LTF",
    "HAWKINCOOK",
    "ADVENZYMES",
    "ASIANPAINT",
    "TTKHLTCARE",
    "DBL",
    "OSWALPUMPS",
    "WSI",
    "SBC",
    "STEELXIND",
    "CPPLUS",
    "HIMATSEIDE",
    "DWARKESH",
    "UTIAMC",
    "ABDL",
    "FIRSTCRY",
    "FILATEX",
    "RAINBOW",
    "RPEL",
    "DLINKINDIA",
    "SANGHVIMOV",
    "MUFIN",
    "MTNL",
    "BLKASHYAP",
    "GODFRYPHLP",
    "GRAVITA",
    "ALICON",
    "ELPROINTL",
    "ALKEM",
    "STOVEKRAFT",
    "MODIS",
    "AWFIS",
    "NAHARINDUS",
    "360ONE",
    "AWHCL",
    "NELCAST",
    "RTNINDIA",
    "BAJAJHIND",
    "SOFTTECH",
    "PPL",
    "ATUL",
    "KPL",
    "LGBBROSLTD",
    "RALLIS",
    "MUTHOOTFIN",
    "BHARATRAS",
    "SYSTMTXC",
    "ELCIDIN",
    "LUPIN",
    "NDRAUTO",
    "JGCHEM",
    "BAJAJINDEF",
    "INDOAMIN",
    "ROLEXRINGS",
    "NAM-INDIA",
    "JBMA",
    "VAIBHAVGBL",
    "KWIL",
    "SHREECEM",
    "ANUP",
    "HAPPSTMNDS",
    "NCC",
    "ACE",
    "KRYSTAL",
    "JUBLFOOD",
    "URBANCO",
    "BEML",
    "ARE&M",
    "KIRLFER",
    "HGS",
    "HERANBA",
    "JYOTISTRUC",
    "BBL",
    "SKFINDUS",
    "BOSCH-HCIL",
    "DHANUKA",
    "BLAL",
    "GFLLIMITED",
    "HEROMOTOCO",
    "NATIONSTD",
    "AEGISLOG",
    "INTELLECT",
    "TERASOFT",
    "JKPAPER",
    "POWERINDIA",
    "MAHSCOOTER",
    "EXCELINDUS",
    "ICRA",
    "M&M",
    "BSOFT",
    "BLS",
    "DBCORP",
    "PRAKASH",
    "BIOCON",
    "TRIVENI",
    "VOLTAS",
    "SUBROS",
    "GSPCROP",
    "KRISHIVAL",
    "PNGSREVA",
    "BECTORFOOD",
    "ASHOKA",
    "INDORAMA",
    "ROSSTECH",
    "CENTURYPLY",
    "NINSYS",
    "HINDZINC",
    "GPTHEALTH",
    "NHPC",
    "KSL",
    "GARFIBRES",
    "SARDAEN",
    "JITFINFRA",
    "TVTODAY",
    "PVSL",
    "PNBHOUSING",
    "AGARIND",
    "IKIO",
    "GOODYEAR",
    "LTFOODS",
    "TNPL",
    "RSL",
    "ADANIENT",
    "LUXIND",
    "HINDPETRO",
    "AMNPLST",
    "CUPID",
    "CENTUM",
    "SYMPHONY",
    "JASH",
    "CYIENTDLM",
    "CONSOFINVT",
    "DHAMPURSUG",
    "BMWVENTLTD",
    "SUNDARMFIN",
    "HINDCOMPOS",
    "TMCV",
    "BAJEL",
    "PIDILITIND",
    "VBL",
    "SRHHYPOLTD",
    "PNB",
    "PGHL",
    "GLENMARK",
    "M&MFIN",
    "SUVEN",
    "ORIENTHOT",
    "ENIL",
    "DAVANGERE",
    "NUVAMA",
    "ADANIGREEN",
    "VELJAN",
    "METROBRAND",
    "VMART",
    "NIRLON",
    "SHOPERSTOP",
    "AFSL",
    "DBOL",
    "BLIL",
    "ENDURANCE",
    "GRANULES",
    "SWANCORP",
    "DCMSHRIRAM",
    "CHEMFAB",
    "TPLPLASTEH",
    "BRIGHOTEL",
    "BAJAJ-AUTO",
    "CARBORUNIV",
    "SHARDACROP",
    "PATANJALI",
    "DOLLAR",
    "IFGLEXPOR",
    "LOTUSDEV",
    "ELIN",
    "PSB",
    "MRF",
    "ADANIENSOL",
    "SAKSOFT",
    "BOSCHLTD",
    "KPITTECH",
    "MANAPPURAM",
    "TIL",
    "KALAMANDIR",
    "EXCELSOFT",
    "VISHNU",
    "THELEELA",
    "CASTROLIND",
    "TASTYBITE",
    "KPRMILL",
    "LANDMARK",
    "STARCEMENT",
    "SURAJEST",
    "RICOAUTO",
    "GPTINFRA",
    "SALSTEEL",
    "GILLETTE",
    "HONDAPOWER",
    "SYNGENE",
    "GCSL",
    "GREAVESCOT",
    "ICEMAKE",
    "ARROWGREEN",
    "EUREKAFORB",
    "MUKANDLTD",
    "SAGILITY",
    "STYLAMIND",
    "TRENT",
    "WELINV",
    "OMPOWER",
    "HEIDELBERG",
    "ABFRL",
    "CRAFTSMAN",
    "SAIPARENT",
    "EMMVEE",
    "CAMLINFINE",
    "THEINVEST",
    "CDSL",
    "SAILIFE",
    "HATSUN",
    "SHALBY",
    "OCCLLTD",
    "IRISDOREME",
    "SYRMA",
    "RPSGVENT",
    "TRITURBINE",
    "CONTROLPR",
    "FDC",
    "MVGJL",
    "SATIA",
    "YATHARTH",
    "MARICO",
    "NRAIL",
    "CSLFINANCE",
    "BIRLAMONEY",
    "ALEMBICLTD",
    "LLOYDSME",
    "TEJASNET",
    "MUNJALSHOW",
    "OMINFRAL",
    "BIGBLOC",
    "OSWALGREEN",
    "BHAGCHEM",
    "ACCELYA",
    "MBAPL",
    "TEMBO",
    "LMW",
    "AXISBANK",
    "LICHSGFIN",
    "AGARWALEYE",
    "STEELCAS",
    "POWERGRID",
    "DRREDDY",
    "AARTIPHARM",
    "UPL",
    "MEDPLUS",
    "BATAINDIA",
    "FAIRCHEMOR",
    "SOLARWORLD",
    "WEL",
    "GRSE",
    "GODREJCP",
    "JSWINFRA",
    "UDS",
    "QUICKHEAL",
    "BALAJITELE",
    "TATAINVEST",
    "REPCOHOME",
    "NYKAA",
    "KABRAEXTRU",
    "JYOTHYLAB",
    "TATATECH",
    "BANKBARODA",
    "MAFATIND",
    "TARC",
    "HCG",
    "KAPSTON",
    "VSSL",
    "HMAAGRO",
    "SWANDEF",
    "SUMICHEM",
    "PROSTARM",
    "MOREPENLAB",
    "ELITECON",
    "MOLDTKPAC",
    "HITECHGEAR",
    "GOPAL",
    "ONWARDTEC",
    "SUNPHARMA",
    "IFBAGRO",
    "HEG",
    "AARTIIND",
    "IPL",
    "RAYMOND",
    "STALLION",
    "MGEL",
    "MANINDS",
    "SATIN",
    "GOKULAGRO",
    "DCW",
    "DODLA",
    "VIVIANA",
    "FMGOETZE",
    "PAGEIND",
    "PFIZER",
    "INDIACEM",
    "ISGEC",
    "KSHINTL",
    "BUTTERFLY",
    "MATRIMONY",
    "SSWL",
    "HMT",
    "MCX",
    "RACLGEAR",
    "DECCANCE",
    "VSTIND",
    "BELRISE",
    "MOTHERSON",
    "RBA",
    "FLUOROCHEM",
    "OLECTRA",
    "CHEVIOT",
    "ASHAPURMIN",
    "INDUSTOWER",
    "KANSAINER",
    "ADVANCE",
    "RADICO",
    "THYROCARE",
    "TVSSCS",
    "TFCILTD",
    "GLOTTIS",
    "AKCAPIT",
    "PNGJL",
    "DALMIASUG",
    "BANKINDIA",
    "TAALTECH",
    "RPGLIFE",
    "CONCORDBIO",
    "GMBREW",
    "CANHLIFE",
    "ORIENTCEM",
    "IMAGICAA",
    "BHARATFORG",
    "SAMMAANCAP",
    "SMSPHARMA",
    "BORANA",
    "MOBIKWIK",
    "GANDHAR",
    "VINCOFE",
    "NSIL",
    "WELCORP",
    "ZFSTEERING",
    "UNIONBANK",
    "WAKEFIT",
    "NMDC",
    "PRIVISCL",
    "DPABHUSHAN",
    "KPEL",
    "EKC",
    "NSLNISP",
    "COCKERILL",
    "RATNAVEER",
    "HATHWAY",
    "INDIAGLYCO",
    "ARVIND",
    "TATAPOWER",
    "MWL",
    "MAXHEALTH",
    "TATACAP",
    "NILKAMAL",
    "KIRIINDUS",
    "DCBBANK",
    "RUPA",
    "SHRIRAMPPS",
    "EASEMYTRIP",
    "ANANDRATHI",
    "IMFA",
    "SHYAMMETL",
    "ANTHEM",
    "BEL",
    "KUANTUM",
    "ARIHANTCAP",
    "FIVESTAR",
    "DELHIVERY",
    "HLVLTD",
    "MAITHANALL",
    "ENTERO",
    "TRANSRAILL",
    "CROMPTON",
    "IGL",
    "SMCGLOBAL",
    "CUMMINSIND",
    "NH",
    "ZIMLAB",
    "BEPL",
    "DRAGARWQ",
    "SBIN",
    "PACEDIGITK",
    "MUFTI",
    "HARDWYN",
    "ACC",
    "INA",
    "THERMAX",
    "GPPL",
    "DALBHARAT",
    "AMBIKCO",
    "ERIS",
    "HINDWAREAP",
    "SUPREMEINF",
    "ASAL",
    "SANATHAN",
    "UTTAMSUGAR",
    "MAANALU",
    "LEMONTREE",
    "ABBOTINDIA",
    "HESTERBIO",
    "CIPLA",
    "VHL",
    "NTPCGREEN",
    "FORCEMOT",
    "ALIVUS",
    "PITTIENG",
    "LXCHEM",
    "ATL",
    "PIXTRANS",
    "ATULAUTO",
    "MHRIL",
    "RAJOOENG",
    "KRSNAA",
    "GOCLCORP",
    "BENGALASM",
    "ANURAS",
    "UFLEX",
    "ZAGGLE",
    "DAMCAPITAL",
    "ULTRACEMCO",
    "WHEELS",
    "AMBUJACEM",
    "RUSTOMJEE",
    "TATASTEEL",
    "THOMASCOOK",
    "EPIGRAL",
    "ASAHIINDIA",
    "EMAMIPAP",
    "HAL",
    "MMP",
    "CARERATING",
    "SKYGOLD",
    "TVSMOTOR",
    "RAJRATAN",
    "SCI",
    "INFOBEAN",
    "ELECON",
    "KISSHT",
    "PARKHOSPS",
    "TMPV",
    "AFFLE",
    "JNKINDIA",
    "IGIL",
    "KOPRAN",
    "GANESHBE",
    "TVSHLTD",
    "LUMAXIND",
    "ICICIAMC",
    "SKFINDIA",
    "PRIMESECU",
    "KICL",
    "JSWENERGY",
    "HNDFDS",
    "STERTOOLS",
    "ORICONENT",
    "MSUMI",
    "RISHABH",
    "BAJAJST",
    "GRASIM",
    "BHARTIHEXA",
    "YUKEN",
    "GREENPANEL",
    "MANALIPETC",
    "SYNCOMF",
    "INDUSINDBK",
    "GRINFRA",
    "ASALCBR",
    "TATACHEM",
    "HINDOILEXP",
    "SHAREINDIA",
    "MASTERTR",
    "UNIMECH",
    "TIPSMUSIC",
    "SWELECTES",
    "UNIENTER",
    "KIRLOSENG",
    "GOODLUCK",
    "RBLBANK",
    "SIGNPOST",
    "BAJAJHFL",
    "CERA",
    "VENUSREM",
    "PUNJABCHEM",
    "AADHARHFC",
    "TI",
    "CMSINFO",
    "FINOPB",
    "AUROPHARMA",
    "DIVGIITTS",
    "MINDACORP",
    "STUDDS",
    "ITCHOTELS",
    "MARUTI",
    "INDIGO",
    "TORNTPHARM",
    "AAVAS",
    "ADOR",
    "SAIL",
    "EICHERMOT",
    "JINDALSTEL",
    "SIYSIL",
    "HINDCOPPER",
    "VEDL",
    "INNOVISION",
    "NILASPACES",
    "RTNPOWER",
    "ASTERDM",
    "V2RETAIL",
    "MEESHO",
    "GABRIEL",
    "ZYDUSLIFE",
    "IMPAL",
    "INDOFARM",
    "SUPRIYA",
    "SFL",
    "PARAGMILK",
    "ATGL",
    "TAJGVK",
    "CEATLTD",
    "KCP",
    "SCHAND",
    "IFCI",
    "JAIBALAJI",
    "VSTTILLERS",
    "LAURUSLABS",
    "APOLLOHOSP",
    "SIRCA",
    "SUDARCOLOR",
    "GMRP&UI",
    "SHAILY",
    "VTL",
    "RKFORGE",
    "EVEREADY",
    "CSBBANK",
    "JSWCEMENT",
    "BESTAGRO",
    "UNIVCABLES",
    "MAHSEAMLES",
    "GODIGIT",
    "MAGADSUGAR",
    "ESABINDIA",
    "MACPOWER",
    "ARSSBL",
    "REDTAPE",
    "GRAPHITE",
    "INDRAMEDCO",
    "ANDHRSUGAR",
    "NRBBEARING",
    "KAMATHOTEL",
    "PDMJEPAPER",
    "WEALTH",
    "HITECHCORP",
    "TVSSRICHAK",
    "MANKIND",
    "SANGAMIND",
    "UBL",
    "AUBANK",
    "SIS",
    "ARTEMISMED",
    "SHANTIGOLD",
    "THANGAMAYL",
    "DREDGECORP",
    "MAHLOG",
    "NUVOCO",
    "VIYASH",
    "MAHABANK",
    "TATACOMM",
    "CLEAN",
    "MARKSANS",
    "WHIRLPOOL",
    "LINCOLN",
    "IDFCFIRSTB",
    "GODREJIND",
    "BLUSPRING",
    "BCLIND",
    "BLUESTONE",
    "DDEVPLSTIK",
    "NOCIL",
    "SDBL",
    "XCHANGING",
    "CCL",
    "CAPILLARY",
    "AARTIDRUGS",
    "NITCO",
    "PASUPTAC",
    "SALASAR",
    "JKTYRE",
    "CRIZAC",
    "DIGITIDE",
    "SGMART",
    "PRICOLLTD",
    "SIGACHI",
    "JBCHEPHARM",
    "FORTIS",
    "COFFEEDAY",
    "JUBLPHARMA",
    "CHEMCON",
    "PAYTM",
    "TCI",
    "ANGELONE",
    "NAHARPOLY",
    "ADVENTHTL",
    "KALYANKJIL",
    "ELECTCAST",
    "HDFCLIFE",
    "RAJPALAYAM",
    "TSFINV",
    "APTUS",
    "VIDHIING",
    "SUKHJITS",
    "SHRIPISTON",
    "AVALON",
    "ELGIEQUIP",
    "RAMKY",
    "KOKUYOCMLN",
    "MFSL",
    "KDDL",
    "JSWDULUX",
    "AIIL",
    "EIHOTEL",
    "DISHTV",
    "HAPPYFORGE",
    "RAMCOIND",
    "RENUKA",
    "RUSHIL",
    "BANARISUG",
    "VINATIORGA",
    "STARHEALTH",
    "ALLCARGO",
    "WELENT",
    "AEROFLEX",
    "BAYERCROP",
    "SURYAROSNI",
    "FINPIPE",
    "FRONTSP",
    "VISACHROME",
    "KEI",
    "FIEMIND",
    "NIBE",
    "HLEGLAS",
    "THEMISMED",
    "CEMPRO",
    "GUJGASLTD",
    "RITCO",
    "SUPRAJIT",
    "SHREEPUSHK",
    "ULTRAMAR",
    "ZFCVINDIA",
    "NLCINDIA",
    "PRECAM",
    "GRAUWEIL",
    "BODALCHEM",
    "DISAQ",
    "BIRLANU",
    "ABINFRA",
    "BLUEDART",
    "AVADHSUGAR",
    "FSL",
    "ONESOURCE",
    "GRPLTD",
    "ALKYLAMINE",
    "PSPPROJECT",
    "RBZJEWEL",
    "DYNAMATECH",
    "BALAMINES",
    "REPRO",
    "SPORTKING",
    "DEEPAKNTR",
    "INDOBORAX",
    "AYMSYNTEX",
    "GUJALKALI",
    "EVERESTIND",
    "BSHSL",
    "ETHOSLTD",
    "JUNIPER",
    "INDOTECH",
    "GLAND",
    "TMB",
    "APOLLOPIPE",
    "ROTO",
    "BOROLTD",
    "GOKEX",
    "MODINATUR",
    "EXIDEIND",
    "BANCOINDIA",
    "ENGINERSIN",
    "IPCALAB",
    "BIL",
    "TIMEX",
    "GKSL",
    "ELDEHSG",
    "VIMTALABS",
    "PAUSHAKLTD",
    "SHREEJISPG",
    "APEX",
    "ICIL",
    "SAFARI",
    "HONASA",
    "BGRENERGY",
    "INDIANHUME",
    "GUJTHEM",
    "RSWM",
    "PARAS",
    "DEEPINDS",
    "GNRL",
    "DEN",
    "JSWSTEEL",
    "BERGEPAINT",
    "VIKRAMSOLR",
    "MONTECARLO",
    "GPIL",
    "VINDHYATEL",
    "PGIL",
    "JARO",
    "HUHTAMAKI",
    "NITTAGELA",
    "CEIGALL",
    "IRIS",
    "JAGSNPHARM",
    "HEXATRADEX",
    "PRIMO",
    "TTML",
    "SMLMAH",
    "FAZE3Q",
    "CAMPUS",
    "ALLDIGI",
    "RAYMONDREL",
    "ALLTIME",
    "GTLINFRA",
    "NEULANDLAB",
    "WENDT",
    "CONFIPET",
    "PCJEWELLER",
    "KSCL",
    "DCMSIL",
    "MMWL",
    "SHREDIGCEM",
    "SOLARA",
    "PVP",
    "IKS",
    "JSFB",
    "SAURASHCEM",
    "ASIANTILES",
    "SENORES",
    "MRPL",
    "RADHIKAJWE",
    "TBOTEK",
    "GATEWAY",
    "TALBROAUTO",
    "MEDIASSIST",
    "EPACKPEB",
    "VHLTD",
    "SEAMECLTD",
    "PNBGILTS",
    "SGFIN",
    "ZOTA",
    "PPLPHARMA",
    "CCCL",
    "GANECOS",
    "ACI",
    "MANINFRA",
    "SPECTRUM",
    "PRECOT",
    "INDOTHAI",
    "NAHARSPING",
    "SANSTAR",
    "SOLARINDS",
    "ACMESOLAR",
    "AEQUS",
    "IDEA",
    "MANORAMA",
    "ABSLAMC",
    "3BBLACKBIO",
    "YASHO",
    "CHENNPETRO",
    "TDPOWERSYS",
    "SPAL",
    "DCAL",
    "PINELABS",
    "HARIOMPIPE",
    "20MICRONS",
    "CRAMC",
    "OLAELEC",
    "UNITEDPOLY",
    "AMRUTANJAN",
    "JINDRILL",
    "SESHAPAPER",
    "SUNCLAY",
    "JSLL",
    "RAMASTEEL",
    "AEROENTER",
    "POWERMECH",
    "SAKAR",
    "VERANDA",
    "SANDHAR",
    "AGIIL",
    "PRABHA",
    "UNIECOM",
    "BLSE",
    "QPOWER",
    "JINDALPOLY",
    "SAMBHV",
    "JPPOWER",
    "HYUNDAI",
    "INDOCO",
    "MODISONLTD",
    "BANSALWIRE",
    "SVLL",
    "SCHNEIDER",
    "ATHERENERG",
    "WESTLIFE",
    "PFOCUS",
    "UEL",
    "KRN",
    "RELTD",
    "HINDALCO",
    "VMM",
    "ASIANENE",
    "SEPC",
    "ZEEMEDIA",
    "RAMCOCEM",
    "UNOMINDA",
    "ACUTAAS",
    "IRMENERGY",
    "KIRANVYPAR",
    "ARIS",
    "SANSERA",
    "UFBL",
    "FISCHER",
    "RUBYMILLS",
    "MAHASTEEL",
    "GROWW",
    "ZSARACOM",
    "SHADOWFAX",
    "AKUMS",
    "AVANTIFEED",
    "AHLWEST",
    "LUMAXTECH",
    "DIACABS",
    "URJA",
    "NATIONALUM",
    "JAYNECOIND",
    "AXISCADES",
    "BCG",
    "NGLFINE",
    "SAYAJIHOTL",
    "AMANTA",
    "PTCIL",
    "NAVNETEDUL",
    "AQYLON",
    "SILVERTUC",
    "TECHNVISN",
    "ANTELOPUS",
    "ABCOTS",
    "IOLCP",
    "NPST",
    "RAIN",
    "COMSYN",
    "GICRE",
    "SCPL",
    "MOTISONS",
]


def get_yf_symbol(nse_symbol):
    """Convert NSE symbol to Yahoo Finance ticker (.NS suffix, URL-encode &)."""
    s = nse_symbol.replace("&", "%26")
    return f"{s}.NS"


def make_session():
    """Return a curl_cffi browser-impersonating session if available, else None."""
    if _HAS_CFFI:
        try:
            return cffi_requests.Session(impersonate="chrome")
        except Exception:
            return None
    return None


def compute_rolling_3m(df):
    """
    TRUE 3-month rolling returns, computed from the SAME ~7 months of data
    already fetched (no extra Yahoo load).
    For every trading day D that has a close ~91 days (3 months) earlier,
    compute the 3-month return ending on D, then summarize the distribution.
    """
    if df is None or df.empty:
        return {}
    closes = df['Close'].dropna()
    if len(closes) < 70:  # need enough for at least a few 3-month windows
        return {}

    dates = closes.index
    rolling = []
    for end_date in dates:
        start_target = end_date - pd.Timedelta(days=91)
        prior = closes[closes.index <= start_target]
        if prior.empty:
            continue
        start_px = float(prior.iloc[-1])
        end_px = float(closes.loc[end_date]) if not isinstance(closes.loc[end_date], pd.Series) else float(closes.loc[end_date].iloc[-1])
        if start_px == 0:
            continue
        rolling.append((end_px - start_px) / start_px * 100.0)

    if not rolling:
        return {}
    arr = np.array(rolling)
    pos = int((arr > 0).sum())
    return {
        "roll3m_avg": round(float(arr.mean()), 2),
        "roll3m_median": round(float(np.median(arr)), 2),
        "roll3m_best": round(float(arr.max()), 2),
        "roll3m_worst": round(float(arr.min()), 2),
        "roll3m_pos_pct": round(pos / len(arr) * 100, 1),
        "roll3m_windows": len(arr),
    }


def compute_avg_entry_return(df):
    """
    Core metric. Fix end = latest close. For every trading day in the
    trailing 1 year, compute (P_last - P_d)/P_d * 100, then summarize.
    Returns dict or {} if insufficient data.
    """
    if df is None or df.empty:
        return {}

    closes = df['Close'].dropna()
    if len(closes) < 30:  # need a reasonable number of entry days
        return {}

    latest_date = closes.index[-1]
    p_last = float(closes.iloc[-1])

    # entry window: trailing 6 months, excluding the latest day itself
    six_mo_ago = latest_date - pd.Timedelta(days=183)
    entries = closes[(closes.index >= six_mo_ago) & (closes.index < latest_date)]
    if entries.empty:
        return {}

    rets = (p_last - entries.values) / entries.values * 100.0
    rets = rets[np.isfinite(rets)]
    if len(rets) == 0:
        return {}

    pos = int((rets > 0).sum())
    return {
        "avg_entry_return": round(float(rets.mean()), 2),
        "median_entry_return": round(float(np.median(rets)), 2),
        "best_entry_return": round(float(rets.max()), 2),
        "worst_entry_return": round(float(rets.min()), 2),
        "pct_profitable_entries": round(pos / len(rets) * 100, 1),
        "entry_days": int(len(rets)),
    }


def _history_with_retry(yf_sym, session, start, end, retries=3):
    """Fetch history with exponential backoff to survive Yahoo rate limits."""
    last_err = None
    for attempt in range(retries):
        try:
            if session is not None:
                ticker = yf.Ticker(yf_sym, session=session)
            else:
                ticker = yf.Ticker(yf_sym)
            df = ticker.history(start=start.strftime('%Y-%m-%d'),
                                end=end.strftime('%Y-%m-%d'),
                                interval='1d', auto_adjust=True)
            if df is not None and not df.empty:
                return df
            last_err = "empty"
        except Exception as e:
            last_err = str(e)
        # backoff: 1.5s, 4s, 9s (+ jitter) before giving up
        if attempt < retries - 1:
            time.sleep((attempt + 1) ** 2 * 1.0 + random.uniform(0.3, 1.2))
    return None


def fetch_stock(symbol, session):
    yf_sym = get_yf_symbol(symbol)
    try:
        end = datetime.today()
        start = end - timedelta(days=210)  # ~6mo + buffer for the entry window

        df = _history_with_retry(yf_sym, session, start, end)
        if df is None or df.empty:
            return None

        stats = compute_avg_entry_return(df)
        if not stats:
            return None
        roll3 = compute_rolling_3m(df)

        price = round(float(df['Close'].dropna().iloc[-1]), 2)
        if len(df) >= 2:
            prev = float(df['Close'].dropna().iloc[-2])
            day_chg = round((price - prev) / prev * 100, 2)
        else:
            day_chg = None

        six_mo_ago = df.index[-1] - pd.Timedelta(days=183)
        df_6m = df[df.index >= six_mo_ago]
        hi52 = round(float(df_6m['High'].max()), 2)
        lo52 = round(float(df_6m['Low'].min()), 2)

        return {
            "symbol": symbol,
            "price": price,
            "day_change_pct": day_chg,
            "avg_entry_return": stats["avg_entry_return"],
            "median_entry_return": stats["median_entry_return"],
            "best_entry_return": stats["best_entry_return"],
            "worst_entry_return": stats["worst_entry_return"],
            "pct_profitable_entries": stats["pct_profitable_entries"],
            "entry_days": stats["entry_days"],
            "roll3m_avg": roll3.get("roll3m_avg"),
            "roll3m_median": roll3.get("roll3m_median"),
            "roll3m_best": roll3.get("roll3m_best"),
            "roll3m_worst": roll3.get("roll3m_worst"),
            "roll3m_pos_pct": roll3.get("roll3m_pos_pct"),
            "roll3m_windows": roll3.get("roll3m_windows"),
            "high_52w": hi52,
            "low_52w": lo52,
            "as_of": datetime.today().strftime('%Y-%m-%d'),
        }
    except Exception as e:
        print(f"  x {symbol}: {str(e)[:80]}")
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=None, help="only fetch first N stocks")
    ap.add_argument("--start", type=int, default=0, help="start index into the list")
    args = ap.parse_args()

    universe = NSE_STOCKS[args.start:]
    if args.limit is not None:
        universe = universe[:args.limit]

    session = make_session()
    sess_note = "curl_cffi (browser TLS)" if session is not None else "plain requests (may rate-limit)"

    print(f"\n{'='*64}")
    print(f"NSE Dashboard 2 — Average Entry-Day Return (6-Month)")
    print(f"Date: {datetime.today().strftime('%d %b %Y %H:%M')}")
    print(f"Universe: {len(NSE_STOCKS)} total | fetching {len(universe)} this run")
    print(f"Session: {sess_note}")
    print(f"{'='*64}\n")

    results, failed = [], []
    for i, symbol in enumerate(universe, 1):
        print(f"[{i:4}/{len(universe)}] {symbol:<14}", end=" ", flush=True)
        row = fetch_stock(symbol, session)
        if row:
            results.append(row)
            avg = f"{row['avg_entry_return']:+.1f}%"
            prof = f"{row['pct_profitable_entries']:.0f}%prof"
            r3 = f"{row['roll3m_avg']:+.1f}%" if row['roll3m_avg'] is not None else "N/A"
            print(f"OK  Rs.{row['price']}  avgEntry={avg}  {prof}  roll3m={r3}")
        else:
            failed.append(symbol)
            print("x  skipped")
        # polite pacing to avoid Yahoo rate limits on large batches
        time.sleep(random.uniform(0.25, 0.6))

    if not results:
        print("\nNo data fetched. Check connection / rate limits.")
        sys.exit(1)

    # If this is a partial run (--start/--limit), merge with existing CSV
    out_csv = DATA_DIR / "results2.csv"
    df_new = pd.DataFrame(results)
    if (args.start > 0 or args.limit is not None) and out_csv.exists():
        try:
            df_old = pd.read_csv(out_csv)
            df_old = df_old[~df_old['symbol'].isin(df_new['symbol'])]
            df_out = pd.concat([df_old, df_new], ignore_index=True)
        except Exception:
            df_out = df_new
    else:
        df_out = df_new

    df_out.to_csv(out_csv, index=False)

    meta = {
        "last_updated": datetime.today().strftime('%Y-%m-%d %H:%M:%S'),
        "total_in_universe": len(NSE_STOCKS),
        "total_in_csv": len(df_out),
        "fetched_this_run": len(results),
        "failed_this_run": failed,
    }
    with open(DATA_DIR / "meta2.json", "w") as f:
        json.dump(meta, f, indent=2)

    print(f"\n{'='*64}")
    print(f"OK  Saved {len(results)} stocks this run -> {out_csv}")
    print(f"    CSV now holds {len(df_out)} total stocks")
    if failed:
        shown = ', '.join(failed[:25])
        more = f" (+{len(failed)-25} more)" if len(failed) > 25 else ""
        print(f"x   Failed ({len(failed)}): {shown}{more}")
    print(f"{'='*64}\n")


if __name__ == "__main__":
    main()
